### ISSUE TITLE
[BUG]: Falsely say No job results found on the page

### ISSUE THREAD

**Issue by sonnyding1** [feder-cr/Jobs_Applier_AI_Agent#978]
### Describe the bug

The agent falsely says No job results found on the page when there are job results found on the page.

### Steps to reproduce

1. Use code from main branch
2. Run the code
3. See error

### Branch

main

### Branch name

main

### Python version

3.12.3

### LLM Used

GPT

### Model used

GPT-4o-mini

### Additional context

Here is the log:

```
2024-12-01 15:10:02.714 | WARNING  | ai_hawk.job_manager:get_jobs_from_page:276 - No job results found on the page. 
 expection: Traceback (most recent call last):
  File "C:\code\Auto_Jobs_Applier_AIHawk\src\ai_hawk\job_manager.py", line 258, in get_jobs_from_page
    jobs_container = self.driver.find_element(By.XPATH, jobs_xpath_query)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\Auto_Jobs_Applier_AIHawk\virtual\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 831, in 
find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\Auto_Jobs_Applier_AIHawk\virtual\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in 
execute
    self.error_handler.check_response(response)
  File "C:\code\Auto_Jobs_Applier_AIHawk\virtual\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, 
in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//ul[contains(@class, 'scaffold-layout__list-container')]"}
  (Session info: chrome=131.0.6778.86)
Stacktrace:
        GetHandleVerifier [0x005A33E3+25059]
        (No symbol) [0x0052CDE4]
        (No symbol) [0x0040BEC3]
        (No symbol) [0x0044FD86]
        (No symbol) [0x0044FFCB]
        (No symbol) [0x0048D952]
        (No symbol) [0x00471F44]
        (No symbol) [0x0048B51E]
        (No symbol) [0x00471C96]
        (No symbol) [0x00443FAC]
        (No symbol) [0x00444F3D]
        GetHandleVerifier [0x00895543+3113795]
        GetHandleVerifier [0x008AA20A+3198986]
        GetHandleVerifier [0x008A29E2+3168226]
        GetHandleVerifier [0x00643250+680016]
        (No symbol) [0x0053572D]
        (No symbol) [0x005329D8]
        (No symbol) [0x00532B75]
        (No symbol) [0x005257D0]
        BaseThreadInitThunk [0x7594FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x7718809E+286]
        RtlGetAppContainerNamedObjectPath [0x7718806E+238]
```

**Comment by bjamin5** [comment]
Also getting this exception

**Comment by innocen3** [comment]
check out this one; we all have the same issue.
#919

**Comment by jkergosi** [comment]
LinkedIn changed their HTML.  Here's the quick fix:

1. Go to job_manager.py
2. Update jobs_container and job_element_list per below:


           ```
            jobs_container = self.driver.find_element(By.XPATH, "//div[@class='scaffold-layout__list ']//ul")

            if scroll:
                jobs_container_scrolableElement = jobs_container.find_element(By.XPATH,"..")
                logger.warning(f'is scrollable: {browser_utils.is_scrollable(jobs_container_scrolableElement)}')

                browser_utils.scroll_slow(self.driver, jobs_container_scrolableElement)
                browser_utils.scroll_slow(self.driver, jobs_container_scrolableElement, step=300, reverse=True)
            
            job_element_list = jobs_container.find_elements(By.XPATH, ".//li[contains(@class, 'scaffold-layout__list-item') and contains(@class, 'ember-view')]")

            if not job_element_list:
                logger.debug("No job class elements found on page, skipping.")
                return []

            return job_element_list
```
